### ISSUE TITLE
Research about simlar websites

### ISSUE THREAD

**Issue by pandevim** [S2W2/Ramabana#1]
# Objective
It's like a subtle competitor analysis. We need to research about similar websites, open source projects, etc.

# Details
Initially available alternative solutions are: 
- https://www.mentimeter.com/
- https://ahaslides.com/
- https://kahoot.com/
- https://pigeonholelive.com/
- https://imakiku.com
- https://www.acadly.com/
- https://meet.ps/
- https://www.classtime.com
- https://www.directpoll.com/
- https://hypersay.com/
- https://socrative.com/
- https://www.polleverywhere.com/
- https://www.beekast.com/
- https://www.wooclap.com/
- https://www.sli.do/

# Deliverable
@raghavpahwa @shafique-md18 @Keyurx11 @pandevim. Everyone should comment on this issue with ideas.

**Comment by pandevim** [comment]
I notices one thing in every similar website, there is always some kind of space available in the website for user to put and start the quiz. So, I suspect there are only two options available for us:

1. Make a pin, code or password
https://www.classtime.com
https://www.beekast.com/
https://www.wooclap.com/
https://www.sli.do/
https://pigeonholelive.com
https://www.mentimeter.com/
https://ahaslides.com/
2. Generate unique link on subdomain and only the person who created can share it
3. Some redirect link
https://meet.ps/
https://kahoot.com/
https://hypersay.com/

Vote and keep your point why you're choosing it.

**Comment by raghavpahwa** [comment]
I think first and second points are good. We can generate a code or password and make a subdomain where there is only one option to input the code.
In this way we would have 2 separate things. One main domain for creating quiz and other for participating.

**Comment by pandevim** [comment]
Wouldn't it be user experience? Like if the main website is https://www.website.com for the creator and https://quiz.website.com for participants. @raghavpahwa

**Comment by raghavpahwa** [comment]
Then we can follow the approach used by mentimeter to solve this issue.
They let users create quiz using mentimeter.com but in order to participate in a quiz, you open menti.com which just has one option which is to input quiz code and the quiz would begin then.
